services:
#region -------------------------------------portainer
  portainer:
    container_name: portainer
    restart: always
    ports:
      - "8080:8000"
      - "9000:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "portainer_data:/data"
#region -------------------------------------portainer

#region -------------------------------------main
  main.api:
    container_name: main.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      # - ASPNETCORE_URLS=http://+:8080
      - "ConnectionStrings__Root=Server=maindb;Database=MainDb;User Id=sa;Password=@Moghanloo368;TrustServerCertificate=True;"
      - "GrpcSettings__HistoryUrl=http://logs.grpc"
    restart: always
    depends_on:
      - maindb
    ports:
      - "8001:8080"

  maindb:
    container_name: main.db
    environment:
      SA_PASSWORD: "@Moghanloo368"
      ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "14330:1433"
    volumes:
      - maindb_data:/var/opt/mssql
#endregion -------------------------------------main

#region -------------------------------------logs
  logs.api:
    container_name: logs.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Root=mongodb://logsdb:27017"
    restart: always
    depends_on:
      - logsdb
    ports:
      - "8003:8080"

  logs.grpc:
    container_name: logs.grpc
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings__Root=mongodb://logsdb:27017"
    restart: always
    depends_on:
      - logsdb
    ports:
      - "8004:8080"

  logsdb:
    container_name: logs.db
    image: mongo
    restart: always
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"
#endregion -------------------------------------logs

#region ----------------------------------------files
  files.api:
    container_name: files.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "DatabaseSettings__Root=Server=filesdb;Port=5432;Database=FilesDb;User Id=admin;Password=@Moghanloo368"
    depends_on: 
      - filesdb
    ports:
      - "8005:80"

  filesdb:
    container_name: filesdb
    image: postgres:15
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=@Moghanloo368
      - POSTGRES_DB=FilesDb
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
#endregion -------------------------------------


